// Generated by https://quicktype.io

export interface Show {
  id: number;
  url: string;
  name: string;
  season: number;
  number: number;
  type: FluffyType;
  airdate: string;
  airtime: string;
  airstamp: string;
  runtime: number | null;
  rating: Rating;
  image: Image | null;
  summary: null | string;
  language: string;
  genres: string[];
  _links: FluffyLinks;
  _embedded: Embedded;
}

export interface Embedded {
  show: ShowClass;
}

export interface ShowClass {
  id: number;
  url: string;
  name: string;
  type: PurpleType;
  language: null | string;
  genres: string[];
  status: Status;
  runtime: number | null;
  averageRuntime: number | null;
  premiered: string;
  ended: null | string;
  officialSite: null | string;
  schedule: Schedule;
  rating: Rating;
  weight: number;
  network: WebChannel | null;
  webChannel: WebChannel;
  dvdCountry: null;
  externals: Externals;
  image: Image;
  summary: null | string;
  updated: number;
  _links: PurpleLinks;
}

export interface PurpleLinks {
  self: Self;
  previousepisode?: Self;
  nextepisode?: Self;
}

export interface Self {
  href: string;
}

export interface Externals {
  tvrage: number | null;
  thetvdb: number | null;
  imdb: null | string;
}

export interface Image {
  medium: string;
  original: string;
}

export interface WebChannel {
  id: number;
  name: string;
  country: Country | null;
  officialSite: null | string;
}

export interface Country {
  name: string;
  code: string;
  timezone: string;
}

export interface Rating {
  average: number | null;
}

export interface Schedule {
  time: string;
  days: Day[];
}

export enum Day {
  Friday = "Friday",
  Monday = "Monday",
  Saturday = "Saturday",
  Sunday = "Sunday",
  Thursday = "Thursday",
  Tuesday = "Tuesday",
  Wednesday = "Wednesday",
}

export enum Status {
  Ended = "Ended",
  InDevelopment = "In Development",
  Running = "Running",
  ToBeDetermined = "To Be Determined",
}

export enum PurpleType {
  Animation = "Animation",
  Documentary = "Documentary",
  Reality = "Reality",
  Scripted = "Scripted",
  Sports = "Sports",
  TalkShow = "Talk Show",
}

export interface FluffyLinks {
  self: Self;
}

export enum FluffyType {
  Regular = "regular",
}

export interface SearchResult {
  score: number;
  show: Show;
}
